POST http://localhost:10842/nextPlay
Content-Type: application/json

{
  "carbon_player": {
    "decision": "minimax",
    "max_plies": 2
  },
  "game_state": {
    "turn_of": 1,
    "workers": [
      {
        "x": 3,
        "y": 3
      },
      {
        "x": 4,
        "y": 4
      },
      {
        "x": 2,
        "y": 2
      },
      {
        "x": 4,
        "y": 2
      }
    ],
    "board": [
      [
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        1,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0
      ]
    ]
  }
}

###
